### ISSUE TITLE
Remove iOS 9.x support?

### ISSUE THREAD

**Issue by agrinman** [kryptco/kryptonite-ios#25]

**Comment by nullpixel1** [comment]
Any reason for this?

**Comment by agrinman** [comment]
Since every communication channel is **completely untrusted**, including Apple's APNS and AWS SNS, we need to encrypt the push notification payload. If the app is terminated by user or the system, we need to send the encrypted signature request in a remote notification payload. However, iOS < 10 does not provide a mechanism to run code upon receipt of a remote notification to decrypt the payload. ***In iOS 10 Apple gave us this: [NotificationServiceExtension](https://developer.apple.com/reference/usernotifications/unnotificationserviceextension).***

Therefore, the push notification that appears is just "Kryptonite request" and the user would be forced to open the app to see the actual contents of the request. Since the user experience for iOS 9 is significantly worse than that of iOS 10, we're debating removing support for it.

**Comment by nullpixel1** [comment]
Ah, right didn't think of that.

I'd still leave support in, it's up to the user if they don't want to update (jailbroken etc)

**Comment by agrinman** [comment]
As of **2.2.1** iOS 9 support will no longer be available. There's such a small amount of iOS 9 users it's worth it to be simplify the code to use iOS 10 notification center APIs.
