### ISSUE TITLE
create SNS endpoint per session so it can be deleted on unpair

### ISSUE THREAD

**Issue by kcking** [kryptco/kryptonite-ios#29]
otherwise remote notifications can still be sent by unpaired computers

**Comment by agrinman** [comment]
Unfortunately, AWS supports only one SNS endpoint per push token. 

**Best Solution:** if adversary grabs your SNSEndpointARN (via `~/.kr/pairing.json`) and is spamming your phone with invalid push notifications, simply reinstall the Kryptonite app from the app store (note that your key will not be destroyed by deleting the app).
