### ISSUE TITLE
"Allow for 3 hours" no longer working after update

### ISSUE THREAD

**Issue by maximumdata** [kryptco/kryptonite-ios#56]
I updated to 2.1.0 on my macbook last week, and now the Allow for 3 hours option is no longer working, and I'm being asked for every request. I was not notified of any update to the app.

**Comment by agrinman** [comment]
What version of Kryptonite iOS are you on (the newest is also 2.1.0)? 
Does the host you SSH into show up as `unknown host`?

**Comment by maximumdata** [comment]
I am on 2.1.0. Sorry, I didn't notice the addition of the "always ask for unknown hosts" option... I don't recall having that when I first installed the app, as the allow for 3 hours choice worked then. All set, thanks for your response!

**Comment by agrinman** [comment]
Thanks for your response! I'm curious why you are getting an `unknown host` -- this should never really happen (with the exception of agent-forwarding which is a known issue). 

Are you using agent-forwarding (`ssh -A`) or is there something else that's causing it to appear?
