### ISSUE TITLE
Known-host Check Exemption for localhost

### ISSUE THREAD

**Issue by achimnol** [kryptco/kryptonite-ios#65]
In my setup, I use a "bastion" (aka SSH jumpbox or proxy) which randomly assigns localhost TCP ports whenever I create a new SSH connection tunneled via an HTTPS WebSocket. For instance, it allows me to connect to a server in a private network when I connect to localhost:12345 where 12345 is a randomly assigned port number.

For the local SSH agent, I can add `StrictHostKeyChecking=no` and `UserKnownHostsFiles=/dev/null` to `.ssh/config`'s `Host localhost` section, to prevent clutters caused by randomized `host:port` pairs (even when connecting to the same destination server).

I'd like to have a simple option to achieve the same effect for localhost in Kryptonite. Also, if this is enabled, all pairs of localhost and random port numbers should be treated as the same target host so that "allow for 3 hours" work with all localhost connections (maybe releated to #63).

**Comment by kcking** [comment]
Hi Joongi,

What software are you using that randomly selects these ports? Setting `UserKnownHostsFiles=/dev/null` is quite dangerous and almost completely defeats the purpose of using SSH as a proxy.

If your version of `kr` is up to date (version 2.1.2), then public keys should be pinned by host-port pair. If your proxy software then deterministically allocated a port for each proxied host, you would be able to take advantage of Kryptonite's public key pinning as-is.

**Comment by achimnol** [comment]
I'm building my own one based on [spoqa/geofront](https://github.com/spoqa/geofront), where the code for the new SSH proxy is not publicly available because it's under development.

I also had the same idea to pin a port number with each destination host, but I thought it may be a useless effort since if we auto-scale the destination hosts (e.g., EC2) then host fingerprints may be changed all the time whenever we terminate existing instances and launch new instances. I mean, storing known hosts permanently may not serve its good in cloud environments with volatile hosts.
Of course, for the sake of maximum security, we should take some inconvenience, but practially, I think providing an option to disable it (enabled by default) would be nice.

**Comment by achimnol** [comment]
After thinking more, I ended up to implement port pinning in my tool using a simple CSV-based automatic configuration.
