### ISSUE TITLE
PGP tweaks

### ISSUE THREAD

**Issue by kcking** [kryptco/kryptonite-ios#68]
- [ ] store 3 most recent userIDs
- [ ] store serialized PGP pubkey so that signature is not required on every `MeRequest`
- [ ] push local notification when new PGP pubkey is signed

**Comment by agrinman** [comment]
(1) fixed in https://github.com/kryptco/kryptonite-ios/commit/12db9f53ad209b82b3a071bf89f49fbebf07700d
