### ISSUE TITLE
iOS 11.2 Beta causes crashing

### ISSUE THREAD

**Issue by xIGBClutchIx** [kryptco/kryptonite-ios#87]
Since I updated to iOS 11.2 Beta like a idiot. The app instantly crashes upon opening.

**Comment by agrinman** [comment]
Are you on a TestFlight build? If so, you can safely download the App Store version and everything will work as expected.

**Comment by xIGBClutchIx** [comment]
Welp that seems to have been the issue. Thought the testflight build was more up to date.

**Comment by agrinman** [comment]
Great — for some reason iOS prevents the TestFlight build from launching on beta builds. We should have notified testers that the TestFlight build is the same as the production build. Apologies for the inconvenience!
