### ISSUE TITLE
Please update for the iPhone X screen size

### ISSUE THREAD

**Issue by spitfire** [kryptco/kryptonite-ios#90]

**Comment by agrinman** [comment]
We’re testing the new version now, it will be out very soon. Please stay tuned!

**Comment by spitfire** [comment]
I’d love to join testing if I can;)

**Comment by agrinman** [comment]
2.3.0 is out now!
https://itunes.apple.com/us/app/kryptonite-by-krypt-co/id1161494806?mt=8
