### ISSUE TITLE
Kryptonite keeps asking me to enable Bluetooth when Bluetooth is disabled

### ISSUE THREAD

**Issue by pinkplus** [kryptco/kryptonite-ios#97]
When I start Kryptonite with Bluetooth disabled, it pops up a dialog asking me to enable Bluetooth. This dialog keeps popping up again and again after I click "OK", until I enable Bluetooth finally.

I'm using 2.3.0.651 on iPhone 6s, iOS 11.2.

**Comment by agrinman** [comment]
Gotcha thanks, this is definitely a bug!
